---
- hosts: all
  become: true
  gather_facts: false
  vars:
   docker_disk: /dev/xvdf
  tasks:

   - name: set fixed hostname
     hostname: name={{inventory_hostname}}

   - name: register host on redhat
     redhat_subscription: autosubscribe=true password={{redhat_password}} username={{redhat_user}} pool="Red Hat OpenShift, Standard Support*" force_register=true

   - name: configing required repositories
     command: subscription-manager repos --disable="*" --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms"  --enable="rhel-7-server-ose-3.7-rpms" --enable="rhel-7-fast-datapath-rpms"

   - name: install additional packages
     yum: name={{item}} state=installed
     with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - python-virtualenv
      - gcc
      - bash-completion
      - sos
      - psacct
      - kexec-tools

   - name: install atomic-openshift-utils
     yum: name=atomic-openshift-utils state=installed enablerepo=rhel-7-server-ose-3.7-rpms

   - name: install docker package
     yum: name=docker state=installed  enablerepo=rhui-REGION-rhel-server-extras

   - name: enable network service
     service: name=network enabled=yes

   - name: stop and disable firewalld
     service: name=firewalld state=stopped enabled=no
     ignore_errors: true

   - name: stop and disable cloudinit
     service: name=cloud-init state=stopped enabled=no

   - name: configure docker-storage-setup config file
     template: src=templates/sysconfig.docker-storage-setup dest=/etc/sysconfig/docker-storage-setup

   - name: configuring docker storage
     command: docker-storage-setup
     args:
      creates: /dev/docker-vg

   - name: start and enable docker service
     service: name=docker state=started enabled=yes
