---
- hosts: all
  become: true
  gather_facts: false
  tasks:

   - name: set fixed hostname
     hostname: name={{inventory_hostname}}

   - name: register host on redhat
     redhat_subscription: autosubscribe=true password={{redhat_password}} username={{redhat_user}} pool="Red Hat OpenShift, Standard Support*" 

   - name: configing required repositories
     command: subscription-manager repos --disable="*" --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms"  --enable="rhel-7-server-ose-3.7-rpms" --enable="rhel-7-fast-datapath-rpms"

   - name: install additional packages
     yum: name={{item}} state=installed
     with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - python-virtualenv
      - gcc
      - bash-completion
      - sos
      - psacct
      - kexec-tools

#   - name: update packages
#     yum: name=* state=latest

   - name: install atomic-openshift-utils
     yum: name=atomic-openshift-utils state=installed enablerepo=rhel-7-server-ose-3.7-rpms

   - name: install docker package
     yum: name=docker state=installed  enablerepo=rhui-REGION-rhel-server-extras


   - name: enable network service
     service: name=network enabled=yes

   - name: stop and disable firewalld
     service: name=firewalld state=stopped enabled=no
     ignore_errors: true

   - name: stop and disable cloudinit
     service: name=cloud-init state=stopped enabled=no


   - name: start and enable docker service
     service: name=docker state=started enabled=yes

#- name: disable StrictHostKeyChecking in ssh client config
#  lineinfile: dest=/etc/ssh/ssh_config line='StrictHostKeyChecking no' state=present insertafter="SendEnv XMODIFIERS"

