---
- hosts: openshift
  become: true
  gather_facts: false
  tasks:

   - name: set fixed hostname
     hostname: name={{inventory_hostname}}

   - name: register host on redhat
     command: subscription-manager register --username='{{redhat_user}}' --password='{{redhat_password}}' --auto-attach --force
     register: redhat_subscription
     until: (redhat_subscription.stdout.find('System already registered') != -1 or redhat_subscription.rc == 0)
     retries: 10
     delay: 10

   - name: get pool ID
     shell: subscription-manager list --available --all|grep "Pool ID:"|awk '{print $3}'
     register: pool_id
     changed_when: false


   - name: attach system to subscription
     shell: subscription-manager attach --pool {{pool_id.stdout}}
     ignore_errors: true
     when: pool_id.stdout != ""

   - name: get list of enabled repos
     shell: subscription-manager repos --list-enabled|grep "Repo ID"|awk '{print $3}'
     changed_when: false
     register: repos
   

   - name: configing required repositories
     command: subscription-manager repos --disable="*" --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms"  --enable="rhel-7-server-ose-3.7-rpms" --enable="rhel-7-fast-datapath-rpms"


